### ISSUE TITLE
Spacebar interaction doesn't work on Nurikabe in demo page

### ISSUE THREAD

**Issue by NateD-MSFT** [tabascq/PuzzleJS#1]
https://tabascq.github.io/PuzzleJS/puzzle-js-demo.html

Nurikabe demo indicates that spacebar is a valid way to toggle tiles.  Not working on Edge Version 113.0.1774.50.  

In general: ideal would be that any "toggle with mouse" functionality also works with spacebar, for accessibility purposes.

**Comment by tabascq** [comment]
Resolved in #5
