### ISSUE TITLE
Does resetAllPuzzleStateOnPage do what's intended?

### ISSUE THREAD

**Issue by roger-wolfson** [tabascq/PuzzleJS#37]
I tried implementing a Reset All button on my puzzle, calling resetAllPuzzleStateOnPage(). This didn't do anything. When I inspected the code and manually made a copy of the function replacing
document.querySelectorAll(".puzzle-grid") 
with 
document.querySelectorAll(".puzzle-grid-content")
, it worked as I expected. This is my first puzzleJS puzzle so I don't want to assume what the existing function does in other contexts, but I'll point this out.

https://github.com/tabascq/PuzzleJS/blob/350efadb04fbf39385fc8ca34af3bbef5febd867/puzzlejs/puzzle.js#L141

**Comment by tabascq** [comment]
This might have been a case I missed when adding subgrid support. I will look into it, thanks!

Note that you might be wanting to use subgrids anyway, as it might result in less work overall. Check out the reference at https://tabascq.github.io/PuzzleJS/reference/reference-subgrids.html.

**Comment by tabascq** [comment]
Fixed, thanks!
